// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dvc.proto

package dvc_protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DVCMessage_DVCMessageType int32

const (
	DVCMessage_Connect        DVCMessage_DVCMessageType = 0
	DVCMessage_JoinConference DVCMessage_DVCMessageType = 1
)

var DVCMessage_DVCMessageType_name = map[int32]string{
	0: "Connect",
	1: "JoinConference",
}
var DVCMessage_DVCMessageType_value = map[string]int32{
	"Connect":        0,
	"JoinConference": 1,
}

func (x DVCMessage_DVCMessageType) String() string {
	return proto.EnumName(DVCMessage_DVCMessageType_name, int32(x))
}
func (DVCMessage_DVCMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dvc_f454a00f565422a7, []int{2, 0}
}

type ConnectMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectMessage) Reset()         { *m = ConnectMessage{} }
func (m *ConnectMessage) String() string { return proto.CompactTextString(m) }
func (*ConnectMessage) ProtoMessage()    {}
func (*ConnectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dvc_f454a00f565422a7, []int{0}
}
func (m *ConnectMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectMessage.Unmarshal(m, b)
}
func (m *ConnectMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectMessage.Marshal(b, m, deterministic)
}
func (dst *ConnectMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectMessage.Merge(dst, src)
}
func (m *ConnectMessage) XXX_Size() int {
	return xxx_messageInfo_ConnectMessage.Size(m)
}
func (m *ConnectMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectMessage proto.InternalMessageInfo

func (m *ConnectMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type JoinConferenceMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ConferenceId         string   `protobuf:"bytes,3,opt,name=conference_id,json=conferenceId,proto3" json:"conference_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinConferenceMessage) Reset()         { *m = JoinConferenceMessage{} }
func (m *JoinConferenceMessage) String() string { return proto.CompactTextString(m) }
func (*JoinConferenceMessage) ProtoMessage()    {}
func (*JoinConferenceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dvc_f454a00f565422a7, []int{1}
}
func (m *JoinConferenceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinConferenceMessage.Unmarshal(m, b)
}
func (m *JoinConferenceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinConferenceMessage.Marshal(b, m, deterministic)
}
func (dst *JoinConferenceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinConferenceMessage.Merge(dst, src)
}
func (m *JoinConferenceMessage) XXX_Size() int {
	return xxx_messageInfo_JoinConferenceMessage.Size(m)
}
func (m *JoinConferenceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinConferenceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_JoinConferenceMessage proto.InternalMessageInfo

func (m *JoinConferenceMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *JoinConferenceMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JoinConferenceMessage) GetConferenceId() string {
	if m != nil {
		return m.ConferenceId
	}
	return ""
}

type DVCMessage struct {
	Type                 DVCMessage_DVCMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=dvc.protocol.DVCMessage_DVCMessageType" json:"type,omitempty"`
	ConnMsg              *ConnectMessage           `protobuf:"bytes,2,opt,name=conn_msg,json=connMsg,proto3" json:"conn_msg,omitempty"`
	JoinConfMsg          *JoinConferenceMessage    `protobuf:"bytes,3,opt,name=join_conf_msg,json=joinConfMsg,proto3" json:"join_conf_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DVCMessage) Reset()         { *m = DVCMessage{} }
func (m *DVCMessage) String() string { return proto.CompactTextString(m) }
func (*DVCMessage) ProtoMessage()    {}
func (*DVCMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dvc_f454a00f565422a7, []int{2}
}
func (m *DVCMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DVCMessage.Unmarshal(m, b)
}
func (m *DVCMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DVCMessage.Marshal(b, m, deterministic)
}
func (dst *DVCMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DVCMessage.Merge(dst, src)
}
func (m *DVCMessage) XXX_Size() int {
	return xxx_messageInfo_DVCMessage.Size(m)
}
func (m *DVCMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DVCMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DVCMessage proto.InternalMessageInfo

func (m *DVCMessage) GetType() DVCMessage_DVCMessageType {
	if m != nil {
		return m.Type
	}
	return DVCMessage_Connect
}

func (m *DVCMessage) GetConnMsg() *ConnectMessage {
	if m != nil {
		return m.ConnMsg
	}
	return nil
}

func (m *DVCMessage) GetJoinConfMsg() *JoinConferenceMessage {
	if m != nil {
		return m.JoinConfMsg
	}
	return nil
}

func init() {
	proto.RegisterType((*ConnectMessage)(nil), "dvc.protocol.ConnectMessage")
	proto.RegisterType((*JoinConferenceMessage)(nil), "dvc.protocol.JoinConferenceMessage")
	proto.RegisterType((*DVCMessage)(nil), "dvc.protocol.DVCMessage")
	proto.RegisterEnum("dvc.protocol.DVCMessage_DVCMessageType", DVCMessage_DVCMessageType_name, DVCMessage_DVCMessageType_value)
}

func init() { proto.RegisterFile("dvc.proto", fileDescriptor_dvc_f454a00f565422a7) }

var fileDescriptor_dvc_f454a00f565422a7 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xb1, 0x4b, 0xc3, 0x50,
	0x10, 0xc6, 0x8d, 0x2d, 0x8d, 0xbd, 0xb4, 0xa1, 0x1c, 0x88, 0x1d, 0x1c, 0x24, 0x1d, 0xd4, 0x25,
	0x60, 0x1d, 0x1c, 0x1c, 0x23, 0x48, 0x85, 0x2c, 0x41, 0x5c, 0x43, 0x7d, 0x39, 0x43, 0x8a, 0xbd,
	0x0b, 0x79, 0x51, 0xe8, 0x3f, 0x2f, 0x92, 0xa3, 0xb6, 0x7d, 0x20, 0x74, 0xfb, 0xf2, 0xe5, 0x7e,
	0xdf, 0x7d, 0xf7, 0x60, 0x58, 0x7c, 0x9b, 0xb8, 0x6e, 0xa4, 0x15, 0x1c, 0xed, 0xa4, 0x91, 0xcf,
	0xe8, 0x16, 0xc2, 0x44, 0x98, 0xc9, 0xb4, 0x29, 0x59, 0xbb, 0x2c, 0x09, 0x2f, 0xc0, 0xff, 0xb2,
	0xd4, 0xe4, 0x55, 0x31, 0xf5, 0xae, 0xbc, 0x9b, 0x61, 0x36, 0xe8, 0x3e, 0x17, 0x45, 0x54, 0xc1,
	0xf9, 0x8b, 0x54, 0x9c, 0x08, 0x7f, 0x50, 0x43, 0x6c, 0xe8, 0x18, 0x81, 0x08, 0x7d, 0x5e, 0xae,
	0x69, 0x7a, 0xaa, 0xae, 0x6a, 0x9c, 0xc1, 0xd8, 0xec, 0x12, 0x3a, 0xa4, 0xa7, 0x3f, 0x47, 0x7b,
	0x73, 0x51, 0x44, 0x3f, 0x1e, 0xc0, 0xd3, 0x5b, 0xf2, 0xb7, 0xe0, 0x11, 0xfa, 0xed, 0xa6, 0x26,
	0x4d, 0x0f, 0xe7, 0xd7, 0xf1, 0xe1, 0x05, 0xf1, 0x7e, 0xee, 0x40, 0xbe, 0x6e, 0x6a, 0xca, 0x14,
	0xc2, 0x07, 0x38, 0x33, 0xc2, 0x9c, 0xaf, 0x6d, 0xa9, 0x45, 0x82, 0xf9, 0xa5, 0x1b, 0xe0, 0xde,
	0x9f, 0xf9, 0xdd, 0x74, 0x6a, 0x4b, 0x7c, 0x86, 0xf1, 0x4a, 0x2a, 0xce, 0xbb, 0x66, 0x4a, 0xf7,
	0x94, 0x9e, 0xb9, 0xf4, 0xbf, 0x4f, 0x92, 0x05, 0xab, 0xad, 0x9d, 0xda, 0x32, 0xba, 0x83, 0xd0,
	0x6d, 0x86, 0x01, 0xf8, 0xdb, 0xad, 0x93, 0x13, 0x44, 0x08, 0xdd, 0x90, 0x89, 0xf7, 0x3e, 0xd0,
	0xfc, 0xfb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xcc, 0x92, 0x9f, 0xb8, 0x01, 0x00, 0x00,
}
